export const LOAD_FIXTURES = 'LOAD_FIXTURES';
export const LOAD_FIXTURES_INITIALIZE = 'LOAD_FIXTURES_INITIALIZE';
export const LOAD_FIXTURES_FAILURE = 'LOAD_FIXTURES_FAILURE';
export const WORLD_CUP_ENDED = 'WORLD_CUP_ENDED';
